### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [4]:
a = []
for i in range(1, 4):
    a.append(i)
b = []
for i in range(1, 10, 2):
    b.append(i**i)
c = []
for i in "stringa":
    c.append(i)

a_comp = [i for i in range(1, 4)]
b_comp = [i**i for i in range(1, 10, 2)]
c_comp = [i for i in "stringa"]

print(a, a_comp)
print(b, b_comp)
print(c, c_comp)


[1, 2, 3] [1, 2, 3]
[1, 27, 3125, 823543, 387420489] [1, 27, 3125, 823543, 387420489]
['s', 't', 'r', 'i', 'n', 'g', 'a'] ['s', 't', 'r', 'i', 'n', 'g', 'a']


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
import numpy as np
def verifica_primo (n: int):
    r = np.array([])
    for i in range(2, n):
        cont = 0
        for c in range(2, (i//2)+1):
            if (i%c == 0):
                cont+=1
        if (cont == 0):
            r = np.append(r, i)
    r = r.astype(int)
    return r

b = verifica_primo(10)
a = np.array([2, 3, 5, 7])
print(a)
print(b)

print(len(a))
print(a.size)

print(a.dtype)

def primo (i:int):
    if (i == 0 or i == 1):
        return False
    cont = 0
    for c in range(2, (i//2)+1):
            if (i%c == 0):
                cont+=1
    if (cont == 0):
        return True
    else:
        return False
    
v = np.array([i for i in range(11) if primo(i)])
print(v)

[2 3 5 7]
[2 3 5 7]
4
4
int64
[2 3 5 7]
int64


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [10]:
a = np.arange(1,10)
print(a)
b = a[1:4]
print(b)
c = a[-1::-1]
print(c)
d = a/c
print(d)

al = list(range(1, 10))
print(al)
bl = al[1:4]
print(bl)
cl = al[-1::-1]
print(cl)
dl = [el/cl[idx] for idx, el in enumerate(al)]
print(dl)

[1 2 3 4 5 6 7 8 9]
[2 3 4]
[9 8 7 6 5 4 3 2 1]
[0.11111111 0.25       0.42857143 0.66666667 1.         1.5
 2.33333333 4.         9.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.1111111111111111, 0.25, 0.42857142857142855, 0.6666666666666666, 1.0, 1.5, 2.3333333333333335, 4.0, 9.0]
